// ================================================================================================
// Copyright (c) 2024, runnindrk
//
// This file is part of Quantum Abysmal.
//
// Quantum Abysmal is free software: you can redistribute it and/or modify it
// as needed, with the intent of making it freely available to everyone.
//
// This project is in its early stages and is provided without any warranties,
// expressed or implied, including but not limited to the warranties of
// merchantability, fitness for a particular purpose, or non-infringement.
//
// Use it at your own risk, and feel free to contribute as the project evolves!
// ================================================================================================

// This file was generated by tools/Codegen.py. Do not edit!

// ================================================================================================

#ifndef QUANTUM_ABYSMAL_SRC_CPUPROVIDER_CODEGEN_UNROLLEDKPMSPARSE_HPP
#define QUANTUM_ABYSMAL_SRC_CPUPROVIDER_CODEGEN_UNROLLEDKPMSPARSE_HPP
                                                                                        \
#define CODEGEN_CPU_PROVIDER_KPM_SPARSE(lattice, a, b, x, y, firstMoment, secondMoment) \
                                                                                        \
    double temp[4] = {};                                                                \
                                                                                        \
    /* Hopping terms (including Hermitian conjugates) */                                \
    temp[0] += lattice.hoppings[0].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 0)];       \
    temp[1] += lattice.hoppings[1].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 1)];       \
    temp[2] += lattice.hoppings[2].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 3)];       \
    temp[3] += lattice.hoppings[3].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 3)];       \
    temp[2] += lattice.hoppings[4].hoppingStrength * b[ARRAY_IDX(x, y, 1, 0, 0)];       \
    temp[1] += lattice.hoppings[5].hoppingStrength * b[ARRAY_IDX(x, y, 1, 0, 3)];       \
    temp[3] += lattice.hoppings[6].hoppingStrength * b[ARRAY_IDX(x, y, 0, 1, 0)];       \
    temp[1] += lattice.hoppings[7].hoppingStrength * b[ARRAY_IDX(x, y, 0, 1, 2)];       \
    temp[2] += lattice.hoppings[8].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 0)];       \
    temp[1] += lattice.hoppings[9].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 3)];       \
    temp[3] += lattice.hoppings[10].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 0)];      \
    temp[1] += lattice.hoppings[11].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 2)];      \
    temp[3] += lattice.hoppings[12].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 2)];      \
    temp[0] += lattice.hoppings[13].hoppingStrength * b[ARRAY_IDX(x, y, -1, 0, 2)];     \
    temp[3] += lattice.hoppings[14].hoppingStrength * b[ARRAY_IDX(x, y, -1, 0, 1)];     \
    temp[0] += lattice.hoppings[15].hoppingStrength * b[ARRAY_IDX(x, y, 0, -1, 3)];     \
    temp[2] += lattice.hoppings[16].hoppingStrength * b[ARRAY_IDX(x, y, 0, -1, 1)];     \
    temp[0] += lattice.hoppings[17].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 2)];      \
    temp[3] += lattice.hoppings[18].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 1)];      \
    temp[0] += lattice.hoppings[19].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 3)];      \
    temp[2] += lattice.hoppings[20].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 1)];      \
                                                                                        \
    /* Output update */                                                                 \
    a[ARRAY_IDX(x, y, 0, 0, 0)] = 2 * temp[0] - a[ARRAY_IDX(x, y, 0, 0, 0)];            \
    a[ARRAY_IDX(x, y, 0, 0, 1)] = 2 * temp[1] - a[ARRAY_IDX(x, y, 0, 0, 1)];            \
    a[ARRAY_IDX(x, y, 0, 0, 2)] = 2 * temp[2] - a[ARRAY_IDX(x, y, 0, 0, 2)];            \
    a[ARRAY_IDX(x, y, 0, 0, 3)] = 2 * temp[3] - a[ARRAY_IDX(x, y, 0, 0, 3)];            \
                                                                                        \
    /* First moment */                                                                  \
    firstMoment += b[ARRAY_IDX(x, y, 0, 0, 0)] * b[ARRAY_IDX(x, y, 0, 0, 0)];           \
    firstMoment += b[ARRAY_IDX(x, y, 0, 0, 1)] * b[ARRAY_IDX(x, y, 0, 0, 1)];           \
    firstMoment += b[ARRAY_IDX(x, y, 0, 0, 2)] * b[ARRAY_IDX(x, y, 0, 0, 2)];           \
    firstMoment += b[ARRAY_IDX(x, y, 0, 0, 3)] * b[ARRAY_IDX(x, y, 0, 0, 3)];           \
                                                                                        \
    /* Second moment */                                                                 \
    secondMoment += a[ARRAY_IDX(x, y, 0, 0, 0)] * b[ARRAY_IDX(x, y, 0, 0, 0)];          \
    secondMoment += a[ARRAY_IDX(x, y, 0, 0, 1)] * b[ARRAY_IDX(x, y, 0, 0, 1)];          \
    secondMoment += a[ARRAY_IDX(x, y, 0, 0, 2)] * b[ARRAY_IDX(x, y, 0, 0, 2)];          \
    secondMoment += a[ARRAY_IDX(x, y, 0, 0, 3)] * b[ARRAY_IDX(x, y, 0, 0, 3)];          \

#endif // QUANTUM_ABYSMAL_SRC_CPUPROVIDER_CODEGEN_UNROLLEDKPMSPARSE_HPP
