// ================================================================================================
// Copyright (c) 2024, runnindrk
//
// This file is part of Quantum Abysmal.
//
// Quantum Abysmal is free software: you can redistribute it and/or modify it
// as needed, with the intent of making it freely available to everyone.
//
// This project is in its early stages and is provided without any warranties,
// expressed or implied, including but not limited to the warranties of
// merchantability, fitness for a particular purpose, or non-infringement.
//
// Use it at your own risk, and feel free to contribute as the project evolves!
// ================================================================================================

// This file was generated by tools/Codegen.py. Do not edit!

// ================================================================================================

#ifndef QUANTUM_ABYSMAL_SRC_CPUPROVIDER_CODEGEN_UNROLLEDKPMSPARSE_HPP
#define QUANTUM_ABYSMAL_SRC_CPUPROVIDER_CODEGEN_UNROLLEDKPMSPARSE_HPP
                                                                                        \
#define CODEGEN_CPU_PROVIDER_KPM_SPARSE(lattice, a, b, x, y, firstMoment, secondMoment) \
                                                                                        \
    double temp[2] = {};                                                                \
                                                                                        \
    /* Hopping terms (including Hermitian conjugates) */                                \
    temp[0] += lattice.hoppings[0].hoppingStrength * b[ARRAY_IDX(x, y, 1, 0, 1)];       \
    temp[0] += lattice.hoppings[1].hoppingStrength * b[ARRAY_IDX(x, y, 0, 1, 1)];       \
    temp[0] += lattice.hoppings[2].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 1)];       \
    temp[1] += lattice.hoppings[3].hoppingStrength * b[ARRAY_IDX(x, y, -1, 0, 0)];      \
    temp[1] += lattice.hoppings[4].hoppingStrength * b[ARRAY_IDX(x, y, 0, -1, 0)];      \
    temp[1] += lattice.hoppings[5].hoppingStrength * b[ARRAY_IDX(x, y, 0, 0, 0)];       \
                                                                                        \
    /* Output update */                                                                 \
    a[ARRAY_IDX(x, y, 0, 0, 0)] = 2 * temp[0] - a[ARRAY_IDX(x, y, 0, 0, 0)];            \
    a[ARRAY_IDX(x, y, 0, 0, 1)] = 2 * temp[1] - a[ARRAY_IDX(x, y, 0, 0, 1)];            \
                                                                                        \
    /* First moment */                                                                  \
    firstMoment += b[ARRAY_IDX(x, y, 0, 0, 0)] * b[ARRAY_IDX(x, y, 0, 0, 0)];           \
    firstMoment += b[ARRAY_IDX(x, y, 0, 0, 1)] * b[ARRAY_IDX(x, y, 0, 0, 1)];           \
                                                                                        \
    /* Second moment */                                                                 \
    secondMoment += a[ARRAY_IDX(x, y, 0, 0, 0)] * b[ARRAY_IDX(x, y, 0, 0, 0)];          \
    secondMoment += a[ARRAY_IDX(x, y, 0, 0, 1)] * b[ARRAY_IDX(x, y, 0, 0, 1)];          \

#endif // QUANTUM_ABYSMAL_SRC_CPUPROVIDER_CODEGEN_UNROLLEDKPMSPARSE_HPP
