# =================================================================================================
# Copyright (c) 2024, runnindrk
#
# This file is part of Quantum Abysmal.
#
# Quantum Abysmal is free software: you can redistribute it and/or modify it
# as needed, with the intent of making it freely available to everyone.
#
# This project is in its early stages and is provided without any warranties,
# expressed or implied, including but not limited to the warranties of
# merchantability, fitness for a particular purpose, or non-infringement.
#
# Use it at your own risk, and feel free to contribute as the project evolves!
# =================================================================================================

from jinja2 import Template

import argparse
import json

# =================================================================================================
# Prepare data for C++ code generation from JSON input

parser = argparse.ArgumentParser(description="Quantum Abysmal Codegen")
parser.add_argument(
    "--json", "-j",
    help="Path to the lattice model JSON file"
)
args = parser.parse_args()

# Load JSON
with open(args.json) as f:
    data = json.load(f)

hoppings = data["lattice"]["hoppings"]

# Collect all unique orbitals
all_orbitals = set()
for hop in hoppings:
    all_orbitals.add(hop["from"])
    all_orbitals.add(hop["to"])

# Sort and assign indices alphabetically
orbital_map = {orb: idx for idx, orb in enumerate(sorted(all_orbitals))}

# Prepare hoppings for C++
cpp_hoppings = []
for hop in hoppings:
    cpp_hoppings.append({
        "latticeHop": hop["delta"] + [0] * (3 - len(hop["delta"])),
        "orbitalHop": [orbital_map[hop["from"]], orbital_map[hop["to"]]],
        "hoppingStrength": hop["value"]
    })

# Add Hermitian conjugate hoppings
hermitian_hoppings = []
for hop in cpp_hoppings:
    if hop["orbitalHop"][0] != hop["orbitalHop"][1] or any(hop["latticeHop"]):
        hermitian_hoppings.append({
            "latticeHop": [-x for x in hop["latticeHop"]],
            "orbitalHop": [hop["orbitalHop"][1], hop["orbitalHop"][0]],
            "hoppingStrength": hop["hoppingStrength"]
        })

all_hoppings = cpp_hoppings + hermitian_hoppings
for idx, hop in enumerate(all_hoppings):
    hop["macro_idx"] = idx

# =================================================================================================
# Copyright Header

COPYRIGHT_HEADER = """\
// ================================================================================================
// Copyright (c) 2024, runnindrk
//
// This file is part of Quantum Abysmal.
//
// Quantum Abysmal is free software: you can redistribute it and/or modify it
// as needed, with the intent of making it freely available to everyone.
//
// This project is in its early stages and is provided without any warranties,
// expressed or implied, including but not limited to the warranties of
// merchantability, fitness for a particular purpose, or non-infringement.
//
// Use it at your own risk, and feel free to contribute as the project evolves!
// ================================================================================================

// This file was generated by tools/Codegen.py. Do not edit!

// ================================================================================================
"""

def GUARD_INIT(guard_name: str) -> str:
    return f"""\

#ifndef {guard_name}
#define {guard_name}
"""

def GUARD_END(guard_name: str) -> str:
    return f"""\


#endif // {guard_name}
"""

# =================================================================================================
# Prepare Lattice Structure Data

lattice_template_str = """
#include "../LatticeStructures.hpp"

inline LatticeStructure CodegenLatticeStructure = 
{
    .dimension = 2,
    .numberOfOrbitals = {{ num_orbitals }},
    .latticeSize = {0, 0, 0},
    .numberOfSites = 1,
    .hamiltonianSize = 1,
    .hoppings = {
        {% for hop in hoppings -%}
        { { {{ hop.latticeHop[0] }}, {{ hop.latticeHop[1] }}, {{ hop.latticeHop[2] }} }, { {{ hop.orbitalHop[0] }}, {{ hop.orbitalHop[1] }} }, {{ hop.hoppingStrength }} },
        {% endfor %}
    },
    .numberOfHoppings = {{ hoppings|length }},
    .minEnergy = 0,
    .maxEnergy = 0,
    .energyScaling = 0,
    .energyShift = 0,
    .boundaryType = PERIODIC
};
"""

# =================================================================================================
# Render CPU Provider Code

def render_cpu_macro(hoppings, num_orbitals):
    lines = []

    lines.append("")
    lines.append("#define CODEGEN_CPU_PROVIDER_KPM_SPARSE(lattice, a, b, x, y, firstMoment, secondMoment)")

    # Temporary variable
    lines.append("")
    lines.append(f"    double temp[{num_orbitals}] = {{}};")

    lines.append("")

    # Hopping terms
    lines.append("    /* Hopping terms (including Hermitian conjugates) */")
    for hop in hoppings:
        lines.append(
            f'    temp[{hop["orbitalHop"][0]}] += lattice.hoppings[{hop["macro_idx"]}].hoppingStrength * b[ARRAY_IDX(x, y, {hop["latticeHop"][0]}, {hop["latticeHop"][1]}, {hop["orbitalHop"][1]})];'
        )

    # Output update
    lines.append("")
    lines.append("    /* Output update */")
    for i in range(num_orbitals):
        lines.append(
            f'    a[ARRAY_IDX(x, y, 0, 0, {i})] = 2 * temp[{i}] - a[ARRAY_IDX(x, y, 0, 0, {i})];'
        )

    # First moment
    lines.append("")
    lines.append("    /* First moment */")
    for i in range(num_orbitals):
        lines.append(
            f'    firstMoment += b[ARRAY_IDX(x, y, 0, 0, {i})] * b[ARRAY_IDX(x, y, 0, 0, {i})];'
        )

    # Second moment
    lines.append("")
    lines.append("    /* Second moment */")
    for i in range(num_orbitals):
        lines.append(
            f'    secondMoment += a[ARRAY_IDX(x, y, 0, 0, {i})] * b[ARRAY_IDX(x, y, 0, 0, {i})];'
        )

    # Calculate padding
    max_len = max(len(line) for line in lines if line.strip())
    tab_size = 4
    space_count = ((max_len + tab_size) // tab_size) * tab_size
    padded_lines = [(line + " " * (space_count - len(line)) + "\\") for line in lines]

    return "\n".join(padded_lines)

# =================================================================================================
# Render CUDA Provider Macro

def render_cuda_macro(hoppings, num_orbitals):
    lines = []

    lines.append("")
    lines.append("#define CODEGEN_CUDA_PROVIDER_KPM_SPARSE(lattice, a, b, x, y, threadIdx, sFirstReduceData, sSecondReduceData)")

    # Temporary variable
    lines.append("")
    lines.append(f"    double temp[{num_orbitals}] = {{}};")

    lines.append("")

    # Hopping terms
    lines.append("    /* Hopping terms (including Hermitian conjugates) */")
    for hop in hoppings:
        lines.append(
            f'    temp[{hop["orbitalHop"][0]}] += lattice.hoppings[{hop["macro_idx"]}].hoppingStrength * b[ARRAY_IDX(x, y, {hop["latticeHop"][0]}, {hop["latticeHop"][1]}, {hop["orbitalHop"][1]})];'
        )

    lines.append("")

    # Output update
    lines.append("    /* Output update */")
    for i in range(num_orbitals):
        lines.append(
            f'    a[ARRAY_IDX(x, y, 0, 0, {i})] = 2 * temp[{i}] - a[ARRAY_IDX(x, y, 0, 0, {i})];'
        )

    lines.append("")

    # First moment
    lines.append("    /* First moment */")
    for i in range(num_orbitals):
        lines.append(
            f'    sFirstReduceData[threadIdx.x] += b[ARRAY_IDX(x, y, 0, 0, {i})] * b[ARRAY_IDX(x, y, 0, 0, {i})];'
        )

    lines.append("")

    # Second moment
    lines.append("    /* Second moment */")
    for i in range(num_orbitals):
        lines.append(
            f'    sSecondReduceData[threadIdx.x] += a[ARRAY_IDX(x, y, 0, 0, {i})] * b[ARRAY_IDX(x, y, 0, 0, {i})];'
        )

    # Calculate padding
    max_len = max(len(line) for line in lines if line.strip())
    tab_size = 4
    space_count = ((max_len + tab_size) // tab_size) * tab_size
    padded_lines = [(line + " " * (space_count - len(line)) + "\\") for line in lines]

    return "\n".join(padded_lines)

# =================================================================================================
# Render Templates

def render_guarded(header, guard, body):
    return header + GUARD_INIT(guard) + body + GUARD_END(guard)

lattice_template = Template(lattice_template_str)
lattice_rendered = render_guarded(
    COPYRIGHT_HEADER,
    "QUANTUM_ABYSMAL_SRC_CODEGEN_LATTICE_HPP",
    lattice_template.render(
        num_orbitals=len(orbital_map),
        hoppings=all_hoppings
    )
)

macro_cuda_rendered = render_guarded(
    COPYRIGHT_HEADER,
    "QUANTUM_ABYSMAL_SRC_CUDAPROVIDER_CODEGEN_UNROLLEDKPMSPARSE_HPP",
    render_cuda_macro(
        num_orbitals=len(orbital_map),
        hoppings=all_hoppings
    )
)

macro_cpu_rendered = render_guarded(
    COPYRIGHT_HEADER,
    "QUANTUM_ABYSMAL_SRC_CPUPROVIDER_CODEGEN_UNROLLEDKPMSPARSE_HPP",
    render_cpu_macro(
        num_orbitals=len(orbital_map),
        hoppings=all_hoppings
    )
)

# =================================================================================================
# Write Files

with open("src/lattice/codegen/Codegen_LatticeStructure.hpp", "w") as f:
    f.write(lattice_rendered)

with open("src/providers/cuda_provider/kpm/density_of_states/standard/codegen/Codegen_UnrolledKpmSparse.hpp", "w") as f:
    f.write(macro_cuda_rendered)

with open("src/providers/cpu_provider/kpm/density_of_states/standard/codegen/Codegen_UnrolledKpmSparse.hpp", "w") as f:
    f.write(macro_cpu_rendered)