// ================================================================================================
// Copyright (c) 2024, runnindrk
//
// This file is part of Quantum Abysmal.
//
// Quantum Abysmal is free software: you can redistribute it and/or modify it
// as needed, with the intent of making it freely available to everyone.
//
// This project is in its early stages and is provided without any warranties,
// expressed or implied, including but not limited to the warranties of
// merchantability, fitness for a particular purpose, or non-infringement.
//
// Use it at your own risk, and feel free to contribute as the project evolves!
// ================================================================================================

// This file was generated by tools/Codegen.py. Do not edit!

// ================================================================================================

#ifndef QUANTUM_ABYSMAL_SRC_CODEGEN_LATTICE_HPP
#define QUANTUM_ABYSMAL_SRC_CODEGEN_LATTICE_HPP

#include "../LatticeStructures.hpp"

inline LatticeStructure CodegenLatticeStructure = 
{
    .dimension = 2,
    .numberOfOrbitals = 2,
    .latticeSize = {0, 0, 0},
    .numberOfSites = 1,
    .hamiltonianSize = 1,
    .hoppings = {
        { { 1, 0, 0 }, { 0, 1 }, -1.0 },
        { { 0, 1, 0 }, { 0, 1 }, -1.0 },
        { { 0, 0, 0 }, { 0, 1 }, -1.0 },
        { { -1, 0, 0 }, { 1, 0 }, -1.0 },
        { { 0, -1, 0 }, { 1, 0 }, -1.0 },
        { { 0, 0, 0 }, { 1, 0 }, -1.0 },
        
    },
    .numberOfHoppings = 6,
    .minEnergy = 0,
    .maxEnergy = 0,
    .energyScaling = 0,
    .energyShift = 0,
    .boundaryType = PERIODIC
};

#endif // QUANTUM_ABYSMAL_SRC_CODEGEN_LATTICE_HPP
